#!/usr/bin/env bash

##############################################################################
##
##  Gradle start up script for POSIX generated by Gradle.
##
##  This is a placeholder. In a real project, this would be generated by
##  running `gradle wrapper` command.
##
##############################################################################

# Attempt to set APP_HOME
# Resolve links: $0 may be a link
PRG="$0"
# Need this for relative symlinks.
while [ -h "$PRG" ] ; do
    ls=`ls -ld "$PRG"`
    link=`expr "$ls" : '.*-> \(.*\)$'`
    if expr "$link" : '/.*' > /dev/null; then
        PRG="$link"
    else
        PRG=`dirname "$PRG"`"/$link"
    fi
done
SAVED="`pwd`"
cd "`dirname \"$PRG\"`/" >&-
APP_HOME="`pwd -P`"
cd "$SAVED" >&-

APP_NAME="Gradle"
APP_BASE_NAME=`basename "$0"`

# Add default JVM options here. You can also use JAVA_OPTS and GRADLE_OPTS to pass JVM options to this script.
DEFAULT_JVM_OPTS=""`"\$APP_HOME/gradle/wrapper/gradle-wrapper.jar" "--no-daemon" "org.gradle.wrapper.BootstrapMainClass" "$@"`
exitCode=$?
exit $exitCode