@if "%DEBUG%" == "" @echo off
@rem ##########################################################################
@rem
@rem  Gradle startup script for Windows generated by Gradle.
@rem
@rem  This is a placeholder. In a real project, this would be generated by
@rem  running `gradle wrapper` command.
@rem
@rem ##########################################################################

@rem Set local scope for the variables with windows NT shell
if "%OS%"=="Windows_NT" setlocal

set DIRNAME=%~dp0
if "%DIRNAME%" == "" set DIRNAME=.
set APP_BASE_NAME=%~n0
set APP_HOME=%DIRNAME%

@rem Add default JVM options here. You can also use JAVA_OPTS and GRADLE_OPTS to pass JVM options to this script.
set DEFAULT_JVM_OPTS=

set JAVA_EXE=%JAVA_EXE_%
if defined JAVA_EXE goto useJavasexe
set JAVA_EXE=java
:useJavasexe

set CMD_LINE_ARGS=%*
set WRAPPER_APP=%APP_HOME%\gradle\wrapper\gradle-wrapper.jar

"%JAVA_EXE%" %DEFAULT_JVM_OPTS% -classpath "%WRAPPER_APP%" org.gradle.wrapper.BootstrapMainClass %CMD_LINE_ARGS%
endlocal
exit /b %ERRORLEVEL%